// Package swagger GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/post": {
            "post": {
                "description": "create new post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "create new post",
                "parameters": [
                    {
                        "description": "CreatePost post",
                        "name": "postCreate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PostCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Post"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorBase"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorBase"
                        }
                    },
                    "500": {
                        "description": "Internal Server ErrorBase",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorBase"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ErrorBase": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "domain.Post": {
            "type": "object",
            "properties": {
                "Content": {
                    "type": "string"
                },
                "Created": {
                    "type": "string"
                },
                "GroupId": {
                    "type": "integer"
                },
                "Id": {
                    "type": "integer"
                },
                "Image": {
                    "type": "string"
                },
                "UserId": {
                    "type": "integer"
                }
            }
        },
        "domain.PostCreate": {
            "type": "object",
            "required": [
                "GroupId"
            ],
            "properties": {
                "Content": {
                    "type": "string"
                },
                "Created": {
                    "type": "string"
                },
                "GroupId": {
                    "type": "integer"
                },
                "UserId": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Pgram backend API",
	Description:      "This is my study project - simple blog mvp.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
