server:
  address: "localhost:8080"
  log_path: "log/gin.log"
  mode: "debug"
  stdout_log: Yes


logger:
  level: "debug"
  json_form: No
  filepath: "log/app.log"
  use_stdout: Yes

postgres:
  user: "api_user"
  password: "12345"
  port: "5432"
  database: "api_db"
  max_conns: 10

static:
  static_dir: "static"


