server:
  address: "sdfj;"
  log_path: ""
  mode: "debug"
  stdout_log: Yes


logger:
  level: "debug"
  json_form: No
  filepath: "path/to/log"
  use_stdout: Yes

postgres:
  user: "api"
  password: "pass"
  port: "23123"
  database: "test"
  max_conns: 10


