server:
  address: "sdfj;"

logger:
  level: "debug"
  json_form: Yes
  filepath: "path/to/log"
  use_stdout: Yes

postgres:
  user: "api"
  password: "pass"
  port: "23123"
  database: "test"
  max_conns: 10
